/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Feb 03 09:08:22 EET 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.alelma.domain;

/*
 * For Table Parts
 */
public class Parts implements java.io.Serializable, Cloneable {
    private PartsKey _key = new PartsKey();

    /* part, PK */
    protected String part;

    /* Desciription */
    protected String desciription;

    /* Return the key object. */
    public PartsKey getKeyObject() {
        return _key;
    }

    /* part, PK */
    public String getPart() {
        return part;
    }

    /* part, PK */
    public void setPart(String part) {
        this.part = part;
        _key.setPart(part);
    }

    /* Desciription */
    public String getDesciription() {
        return desciription;
    }

    /* Desciription */
    public void setDesciription(String desciription) {
        this.desciription = desciription;
    }

    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof Parts))
            return false;

        Parts bean = (Parts) obj;

        if (this.part == null) {
            if (bean.part != null)
                return false;
        }
        else if (!this.part.equals(bean.part)) 
            return false;

        if (this.desciription == null) {
            if (bean.desciription != null)
                return false;
        }
        else if (!this.desciription.equals(bean.desciription)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        Parts bean = new Parts();
        bean.part = this.part;
        bean.desciription = this.desciription;
        return bean;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("part").append(" = ").append(part).append("]").append(sep);
        sb.append("[").append("desciription").append(" = ").append(desciription).append("]").append(sep);
        return sb.toString();
    }
}