/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Feb 03 09:08:22 EET 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.alelma.domain;

public class PartsKey implements java.io.Serializable, Cloneable {
    /* part */
    protected String part;

    /* part */
    public String getPart() {
        return part;
    }

    /* part */
    public void setPart(String part) {
        this.part = part;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        if (part != null)  
            hashCode += part.hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof PartsKey))
            return false;

        PartsKey key = (PartsKey) obj;

        if (this.part == null) {
            if (key.part != null)
                return false;
        }
        else if (!this.part.equals(key.part)) 
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        PartsKey key = new PartsKey();
        key.part = this.part;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("part").append(" = ").append(part).append("]");
        return sb.toString();
    }
}