/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Feb 03 11:50:55 EET 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.alelma.domain;

public class ArizaKey implements java.io.Serializable, Cloneable {
    /* id */
    protected long id;

    /* id */
    public long getId() {
        return id;
    }

    /* id */
    public void setId(long id) {
        this.id = id;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Long(id).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof ArizaKey))
            return false;

        ArizaKey key = (ArizaKey) obj;

        if (this.id != key.id)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        ArizaKey key = new ArizaKey();
        key.id = this.id;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("id").append(" = ").append(id).append("]");
        return sb.toString();
    }
}