/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Sat Feb 03 09:08:22 EET 2018
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.alelma.domain.orm;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;
import com.alelma.domain.*;
import com.alelma.domain.dao.PartsDAO;

/**
 * This class provides methods to populate DB Table of Parts
 */
public class PartsDAOImpl implements PartsDAO {
    /* SQL to insert data */
    private static final String SQL_INSERT =
        "INSERT INTO Parts ("
        + "part, Desciription"
        + ") VALUES (?, ?)";

    /* SQL to select data */
    private static final String SQL_SELECT =
        "SELECT "
        + "part, Desciription "
        + "FROM Parts WHERE "
        + "part = ?";

    /* SQL to update data */
    private static final String SQL_UPDATE =
        "UPDATE Parts SET "
        + "Desciription = ? "
        + "WHERE "
        + "part = ?";

    /* SQL to delete data */
    private static final String SQL_DELETE =
        "DELETE FROM Parts WHERE "
        + "part = ?";

    /**
     * Create a new record in Database.
     * @param bean   The Object to be inserted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void create(Parts bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_INSERT);
            ps.setString(1, bean.getPart());
            ps.setString(2, bean.getDesciription());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Retrive a record from Database.
     * @param beanKey   The PK Object to be retrived.
     * @param conn      JDBC Connection.
     * @exception       SQLException if something is wrong.
     */
    public Parts load(PartsKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conn.prepareStatement(SQL_SELECT);
            ps.setString(1, key.getPart());
            rs = ps.executeQuery();
            List results = getResults(rs);
            if (results.size() > 0)
                return (Parts) results.get(0);
            else
                return null;
        }finally {
            close(rs);
            close(ps);
        }
    }

    /**
     * Update a record in Database.
     * @param bean   The Object to be saved.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void update(Parts bean, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_UPDATE);
            ps.setString(1, bean.getDesciription());
            ps.setString(2, bean.getPart());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }

    /**
     * Create a new record in Database.
     * @param bean   The PK Object to be deleted.
     * @param conn   JDBC Connection.
     * @exception    SQLException if something is wrong.
     */
    public void delete(PartsKey key, Connection conn) throws SQLException {
        PreparedStatement ps = null;
        try {
            ps = conn.prepareStatement(SQL_DELETE);
            ps.setString(1, key.getPart());
            ps.executeUpdate();
        }finally {
            close(ps);
        }
    }
    
    /**
     * Populate the ResultSet.
     * @param rs     The ResultSet.
     * @return       The Object to retrieve from DB.
     * @exception    SQLException if something is wrong.
     */
    protected List<Parts> getResults(ResultSet rs) throws SQLException {
        List results = new ArrayList<Parts>();
        while (rs.next()) {
            Parts bean = new Parts();
            bean.setPart(rs.getString("part"));
            bean.setDesciription(rs.getString("Desciription"));
            results.add(bean);
        }
        return results;
    }

    /**
     * Close JDBC Statement.
     * @param stmt  Statement to be closed.
     */
    protected void close(Statement stmt) {
        if (stmt != null) {
            try {
                stmt.close();
            }catch(SQLException e){}
        }
    }

    /**
     * Close JDBC ResultSet.
     * @param rs  ResultSet to be closed.
     */
    protected void close(ResultSet rs) {
        if (rs != null) {
            try {
                rs.close();
            }catch(SQLException e){}
        }
    }
}